### PR TITLE
Add support for nvim-navic highlight groups

### PR DESCRIPTION
**Pull request by cagucor**
Added highlights for [nvim-navic](https://github.com/SmiteshP/nvim-navic) with some colours which make sense to me. 

This pull request resolves issue #42

### CODE REVIEW

**Comment by rmehri01** [comment]
Hey, thanks for this! Like I said in the issue, I think it would be nice for this plugin to reuse some existing highlights by default but we can merge this in the mean time. Do you mind if I change some of the highlights to make them a bit more consistent?

**Comment by cagucor** [comment]
Feel free to change it up!

**Comment by rmehri01** [comment]
Thanks! What do you think? Also updated the docs while I was there

**Comment by cagucor** [comment]
Looks good to me

**Review by rmehri01 — APPROVED** [review]
Great, thanks again!

**Pull request merged**
