### PR TITLE
Onenord Light Theme

### LINKED ISSUE #15: Feature request - light mode
Hi, I love the combination of one and nord theme. Nord theme doesn't support light mode, but one theme has light mode. Maybe this is too much to ask but what do you think about having a light mode for onenord? At first, we can build it from onelight's colors, and then create our own light version of nord later where we see fit. 

If you are interested, I'm willing to give a hand if you need any help 😄

### PR DESCRIPTION
**Pull request by rmehri01**
Closes #15

### CODE REVIEW

**Comment by rmehri01** [comment]
Feel free to try it out and leave any suggestions @dakennguyen! I'll change the variations of colors (such as dark and light) once we decide that the base ones are good.

**Comment by rmehri01** [comment]
Oh yeah I forgot to mention, you can do `:colorscheme onenord` and `:colorscheme onenordlight` now to see the difference or configure it in the setup function using `style = "dark/light"`.

**Comment by dakennguyen** [comment]
> Feel free to try it out and leave any suggestions @dakennguyen! I'll change the variations of colors (such as dark and light) once we decide that the base ones are good.

I tried it out. I have a dilemma 😂 . The color looks great on my macbook's screen, but for my 27inch monitor, it's a little too bright for me. Especially for `cyan` and `yellow` (I tested with Ruby)
image

I tried to dim the background a little bit with this:
```
bg = #eeeeee
colors.active = "#e5e5e5"
colors.float = "#e5e5e5"
colors.highlight = "#e5e5e5"
colors.selection = "#e5e5e5"
```
image
But then seems like the whole color palette needs to be adjusted too. The background doesn't go well with the current colors
It's up to you then cause I'm also no expert on this 😄  

Also, what do you think about relying on `vim.opt.background = 'dark'/'light'` to toggle between the 2 modes? I see many other schemes do it this way

**Comment by rmehri01** [comment]
> I tried it out. I have a dilemma 😂 . The color looks great on my macbook's screen, but for my 27inch monitor, it's a little too bright for me. Especially for `cyan` and `yellow` (I tested with Ruby)

Good to know! I'm still experimenting with some colors, I think a gold or more brownish color like `#9B8B38` would be better instead of yellow since yellow doesn't go well on white. I'll also try darkening some of the others.

> But then seems like the whole color palette needs to be adjusted too. The background doesn't go well with the current colors
> It's up to you then cause I'm also no expert on this 😄

Yeah I tried it out too and that seems to be the case, I think I like the brighter background more but I'm not an expert either 😅

> Also, what do you think about relying on `vim.opt.background = 'dark'/'light'` to toggle between the 2 modes? I see many other schemes do it this way

I think this is a good idea, I'll add it in!

**Comment by rmehri01** [comment]
@dakennguyen Could you try out the new colors, hopefully they are a bit better!

**Comment by dakennguyen** [comment]
@rmehri01 awesome!! I love the new color palette!!! Could you also rework the `diff_*` section color? Then no more comment from me. Let's merge and see feedback from the others 😄  Thank you!

**Comment by rmehri01** [comment]
Yup! I'll be sure to do the lighter and darker colors as well, I just wanted to confirm the base colors.

**Comment by rmehri01** [comment]
Alright, I think this should be good. Thanks again for the help and suggestion @dakennguyen!

**Pull request merged**
