### PR TITLE
feat: add iTerm theme

### PR DESCRIPTION
**Pull request by jose-elias-alvarez**
Thanks for the great theme! It's been a while since I found something so pleasant and usable.

This PR adds a simple port of the Alacritty theme to iTerm.

### CODE REVIEW

**Comment by rmehri01** [comment]
Hey there, thanks for the pr and the kind words! 

I think Alacritty is a bit of a special case since it seems to be a bit brighter than Kitty for example but let me know if it's different for you. I made the Kitty colors a bit brighter because of this so I would recommend following those. 

One more thing is that I think the [normal Nord theme for iTerm](https://github.com/arcticicestudio/nord-iterm2) has some pretty nice defaults, so I would build off starting from that for some of the options like cursor guide and you can do so too if you'd like!

**Comment by rmehri01** [comment]
I'll also tag @shMorganson since they seemed to have an iTerm theme too and might have some suggestions!

**Comment by jose-elias-alvarez** [comment]
Got it. I tweaked it to use the original Nord theme as a base and the colors from the Kitty theme instead. On my screen, Kitty and iTerm look identical. 

I don't really use the cursor guide, so I'm not sure what it's supposed to look like, but I left it alone for now.

**Comment by rmehri01** [comment]
This looks great, thanks again!

**Review by rmehri01 — APPROVED** [review]

**Pull request merged**
